# Generated by Django 4.1.3 on 2022-11-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_inwarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('total_amt', models.FloatField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('shop_name', models.CharField(blank=True, max_length=50)),
                ('shop_mobile', models.CharField(max_length=50)),
                ('shop_address', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'verbose_name_plural': 'Distribution',
            },
        ),
    ]
