# Generated by Django 4.1.3 on 2022-11-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_distribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='sale_date',
            new_name='issued_date',
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='shop_mobile',
            new_name='shop_mobile_number',
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='total_amt',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='inwarding',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='inwarding',
            old_name='pur_date',
            new_name='recieved_date',
        ),
        migrations.RenameField(
            model_name='inwarding',
            old_name='total_amt',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='distribution',
            name='shop_name',
            field=models.CharField(max_length=50),
        ),
    ]
