# Generated by Django 4.1.3 on 2022-11-16 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_distribution_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='issue',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.distribution'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='issued_quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='recieved_quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='recieving',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.inwarding'),
        ),
    ]
